management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    ru.alxdv.monitoring: INFO
    org.springframework: INFO

